(#697) Update Chocolatey API calling
chocolatey/ChocolateyGUI pull request #861
Opened 2021-06-21 10:59 UTC by AdmiringWorm

This commit makes changes to how the Chocolatey API is being called,
which then allows the original logging that Chocolatey implements
to still happen when we add our own Serilog logger.

This change depends on a new change in the Chocolatey codebase,
and a new release of the program.

fixes #697

Heavily dependent on Chocolatey PR https://github.com/chocolatey/choco/pull/2295

Do Not Merge until a new release of Chocolatey with the PR mentioned is released.

2021-06-21 15:07 UTC, gep13 requested changes
Just a few minor nit picks

2021-06-21 15:07 UTC, gep13 commented on Source/ChocolateyGui.Common.Windows/Bootstrapper.cs
> +                var choco = Lets.GetChocolatey(false);
For the bare boolean parameter here, can you use the named parameter syntax?

```suggestion
                var choco = Lets.GetChocolatey(initializeLogging: false);
```

2021-06-21 15:07 UTC, gep13 commented on Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
> +            _choco = Lets.GetChocolatey(false).SetCustomLogging(new SerilogLogger(Logger, _progressService), false, true);
```suggestion
            _choco = Lets.GetChocolatey(initializeLogging: false).SetCustomLogging(new SerilogLogger(Logger, _progressService), logExistingMessages: false, addToExistingLoggers: true);
```

2021-06-21 15:07 UTC, gep13 commented on Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
> +                var choco = Lets.GetChocolatey(false).SetCustomLogging(logger, false, true);
```suggestion
                var choco = Lets.GetChocolatey(initializeLogging: false).SetCustomLogging(logger, logExistingMessages: false, addToExistingLoggers: true);
```

2021-06-21 15:07 UTC, gep13 commented on Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
> +                var choco = Lets.GetChocolatey(false).SetCustomLogging(logger, false, true);
```suggestion
                var choco = Lets.GetChocolatey(initializeLogging: false).SetCustomLogging(logger, logExistingMessages: false, addToExistingLoggers: true);
```

2021-06-21 15:07 UTC, gep13 commented on Source/ChocolateyGui.Common.Windows/Services/ChocolateyService.cs
> +                var choco = Lets.GetChocolatey(false).SetCustomLogging(logger, false, true);
```suggestion
                var choco = Lets.GetChocolatey(initializeLogging: false).SetCustomLogging(logger, logExistingMessages: false, addToExistingLoggers: true);
```

2021-06-21 15:08 UTC, gep13 commented
@AdmiringWorm the failing AppVeyor build is due to the referenced Chocolatey.dll, so this isn't anything to worry about just now.

2022-01-21 07:46 UTC, gep13 commented
@AdmiringWorm is this one we should be looking to pull into 0.20.0 as well, now that a new version of Chocolatey has been released?

2022-01-21 09:05 UTC, AdmiringWorm commented
@gep13 if I remember correctly, the intention was to include this PR in the next version that is released after the code in the Chocolatey codebase was added.

So yeah, I think it would be appropriate to include the change in 0.20.0.
May however need to bump the minimum requirement of Chocolatey specified in the nuspec file though (I don't remember at the top of my head when the necessary code changes went into Chocolatey itself, but I'll figure it out and update the PR).

2022-01-21 09:53 UTC, AdmiringWorm commented
@gep13 I have rebased this PR, and checked if we had to update anything else. There should not be any additional changes being necessary (assuming the current PR build succeeds).

2022-01-27 10:43 UTC, AdmiringWorm commented
@gep13 I have rebased this PR to include the latest changes from the develop branch.

2022-01-27 12:10 UTC, gep13 approved these changes
LGTM!

2022-01-27 13:39 UTC, merged

2022-01-27 13:39 UTC, gep13 commented
@AdmiringWorm thanks for getting this sorted out, it will be great to have the Chocolatey logs in the _right_ place when executing through Chocolatey GUI.